YorkAARGH/York-Dev

- app.js
- commands.js
- package.json
I did some testing.  Not extremely thorough testing, but it didn't break.
> random improvements

- monitors/monitor.js
Added a check for whether a message is "substantial" enough to count for
points, using various metrics. Feel free to edit this algorithm however
you wish.
> Enhancement to the points awarding system

- commands/google.js
- package.json
Google command is now in a pretty embed, shows top 5 results, and has titles, thumbnails & snippets.
It also will return a text version if there aren't embed permissions for the bot.
> Updated Google command

- commands/google.js
Fixes books links from Google, they are formatted differently apparently
This will also accidentally fix any other errors related to the result URL being formatted differently
> google fixes

- assets/dashboard/public/dashboard.css
- assets/dashboard/templates/admin.ejs
- assets/dashboard/templates/autherror.ejs
- assets/dashboard/templates/blocks/header.ejs
- assets/dashboard/templates/commands.ejs
- assets/dashboard/templates/dashboard.ejs
- assets/dashboard/templates/index.ejs
- assets/dashboard/templates/manage.ejs
- assets/dashboard/templates/members.ejs
- assets/dashboard/templates/stats.ejs
- functions/dashboard.js
- package.json
Brought the dashboard up to speed with the official guidebot repo
> Updated Dashboard

- README.md
> Correct Typos

- commands/fun/magic8.js
- events/ready.js
- Improves consistency, some `setInterval` and `setTimeout` had a space before `async` and some didn't.
- Removed async/await where it was unnecessary
> Code-style consistency

- assets/issueList.json
I don't remember the error code etc, so I'm just adding this part
> Added defaultChannel to the issueList

- assets/json/issueList.json
* Improved `guild.defaultChannel` auto-response
* Also fixed some spacing that was bothering me 😛
> Improved defaultChannel auto-response

- assets/dashboard/templates/commands.ejs
?pls @work 
Collapsing groups  of commands b catogories.
> Collapsable groups?

- commands/social/leaderboard.js
> Pages in the leaderboard

- base/Social.js
- commands/social/daily.js
- commands/utilities/reminder.js
-r flag on the daily will create a reminder for 24h to collect daily as well as collect daily
> Reminder: use to,me,in inside your action & -r flag on daily

- commands/utilities/google.js
Fixes searching terms like "google"
> Google: fix

- README.md
> One more change in README.MD

- commands/utilities/google.js
- Forces results in English, and geolocation set to UK
- Removes Google Image results
- Changes the way URLs are displayed (only shows domain name in title)
- ENFORCES EMBED LIMITS, NO MORE ERRORS AND NO MORE EXCEEDED EMBEDS
> Google: multiple fixes

- commands/utilities/google.js
Issue with commands erroring because of thumbnail URL + errors with regex
> Hawtfix: Google command

- base/Social.js
Claim daily in server: \`${message.guild.name}\` add to reminder
> Server name in daily.

- base/Social.js
Fixes this issue. http://this-is-totally-a.serious-website.com/zYFR9.png
> Slight reminder fix

- commands/utilities/google.js
I forgot to escape a dash in regex, causing a thing to puke and the command to fail silently
also added insurance in case i still fucked it up, so it doesnt err but runs instead
> hotfix: google command

- commands/utilities/google.js
embed limit exceeded due to my cognitive shortcomings
fixed
> *sigh* another hotfix, the last one this time pinkyswears

- commands/fun/fml.js
> Quick Spelling Fix

- commands/utilities/braille.js
- package.json
https://andrew-is.online/i/qf69e.png
> Braille command
